name: Lint commit message

on: [ push ]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            -   name: Clone
                uses: actions/checkout@v3

            -   name: Setup node 14
                uses: actions/setup-node@v3
                with:
                    node-version: '14'
                    check-latest: true

            -   name: Install commitlint
                run: npm install -g @commitlint/cli @commitlint/config-conventional

            -   name: Lint commit message
                run: echo "${{ github.event.head_commit.message }}" | commitlint --config .github/commitlint.config.js
