name: Unit tests

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Clone
                uses: actions/checkout@v2

            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    distribution: adopt
                    java-version: 17

            -   name: Execute unit tests
                run: mvn test
