name: Unit tests

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Clone
                uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution: adopt
                    java-version: 21

            -   name: Execute unit tests
                run: mvn test
