name: Release

on:
    release:
        types: [ created ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Clone
                uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution: adopt
                    java-version: 21

            -   name: Package
                run: mvn package

            -   name: Get artifact name
                id: artifact
                run: echo "name=$(cd target && ls *.jar && cd ..)" >> $GITHUB_OUTPUT

            -   name: Upload artifact
                uses: djnicholson/release-action@v2.11
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    tag-name: ${{ github.ref_name }}
                    asset-name: '${{steps.artifact.outputs.name}}'
                    file: 'target/${{steps.artifact.outputs.name}}'
